name: Commit Stage

on:
  push:
    branches:
      - main

jobs:
  e2e-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        run: yarn bootstrap
        shell: bash

      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
          record: false
          start: yarn start
          wait-on: 'http://localhost:5001'
          browser: chrome